name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./my-angular-app  # Adjust if needed

      - name: Build application
        run: npm run build --prod --aot --build-optimizer=false
        working-directory: ./my-angular-app  # Adjust if needed

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 18.117.131.36
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}  # Add your private key as a GitHub secret
          port: 22
          source: "./my-angular-app/dist/my-angular-app/*"
          target: "/home/ubuntu/praveen_thati_cicd/my-angular-app/dist/my-angular-app/"
